import { useEffect } from "react";
import Head from "next/head";

import * as $ from "./index.styled";
import useWardrobeStore from "@/stores/wardrobeStore";

import Stand from "@/components/modules/stand";
import Module2 from "@/components/modules/module2";

const index = () => {
  const { height, setViewportSize, mm } = useWardrobeStore((state) => ({
    height: state.height,
    setViewportSize: state.setViewportSize,
    mm: state.mm,
  }));

  useEffect(() => {
    setViewportSize({
      width: window.innerWidth,
      height: window.innerHeight,
    });

    const handleResize = () => {
      setViewportSize({
        width: window.innerWidth,
        height: window.innerHeight,
      });
    };

    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Nakonfigurujte si vlastnu skriňu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <$.Main>
        <$.Wardrobe $height={mm * height}>
          <Stand />
          <Module2 />
          <Stand />
          <Module2 />
          <Stand />
          <Module2 />
          <Stand />
        </$.Wardrobe>
      </$.Main>
    </>
  );
};

export default index;
