import Head from "next/head";
import MobileMenu from "@/layouts/web/MobileMenu";
import Header from "@/layouts/web/Header";
import Hero from "@/layouts/web/Hero";
import Benefits from "@/layouts/web/Benefits";
import OrderSection from "@/layouts/web/OrderSection";
import VisualizationSection from "@/layouts/web/VisualizationSection";
import FAQ from "@/components/web/FAQ";
import Team from "@/components/web/Team";
import Contact from "@/components/web/Contact";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileMenu />
      <Header />
      <Hero />
      <Benefits />
      <OrderSection />
      <VisualizationSection />
      <FAQ />
      <Team />
      <Contact />
    </>
  );
};

export default Home;
