import Head from "next/head";
import MobileMenu from "@/layouts/web/MobileMenu";
import Header from "@/layouts/web/Header";
import Hero from "@/layouts/web/Hero";
import Benefits from "@/layouts/web/Benefits";
import SplitContent from "@/layouts/web/SplitContent";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileMenu />
      <Header />
      <Hero />
      <Benefits />
      <SplitContent />
    </>
  );
};

export default Home;
